apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app1
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: argo-local-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: application-of-applications-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      sources:
        - repositoryType: git
          repoURL: https://github.com/saiakhil23/solar-system.git
          targetRevision: main
          path: kubernetes/development
      destination:
        namespace: akhil
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: false
        syncOptions:
          - CreateNamespace=true
          - PruneLast=false
